version: '3.5'

services: 
    app:
        image: node:12-alpine
        volumes: 
            - ./:/app
        build: .
        working_dir: /app
        ports: 
            - 3000:3000
        command: npm start