export const ANHADIR_ITEM_AL_CARRITO = 'ANHADIR_ITEM_AL_CARRITO';
export const ELIMINAR_ITEM_DEL_CARRITO = 'ELIMINAR_ITEM_DEL_CARRITO';
export const CARRITO_GUARDAR_ENVIO = 'CARRITO_GUARDAR_ENVIO';
export const CARRITO_GUARDAR_PAGO = 'CARRITO_GUARDAR_PAGO';
export const VACIAR_CARRITO = 'VACIAR_CARRITO';