export const PEDIDO_CREADO_REQUEST = 'PEDIDO_CREADO_REQUEST';
export const PEDIDO_CREADO_SUCCESS = 'PEDIDO_CREADO_SUCCESS';
export const PEDIDO_CREADO_FAIL = 'PEDIDO_CREADO_FAIL';
export const PEDIDO_CREADO_RESET = 'PEDIDO_CREADO_RESET';

export const PEDIDO_DETALLES_REQUEST = 'PEDIDO_DETALLES_REQUEST';
export const PEDIDO_DETALLES_SUCCESS = 'PEDIDO_DETALLES_SUCCESS';
export const PEDIDO_DETALLES_FAIL = 'PEDIDO_DETALLES_FAIL';

export const LISTA_PEDIDOS_USUARIO_REQUEST = 'LISTA_PEDIDOS_USUARIO_REQUEST';
export const LISTA_PEDIDOS_USUARIO_SUCCESS = 'LISTA_PEDIDOS_USUARIO_SUCCESS';
export const LISTA_PEDIDOS_USUARIO_FAIL = 'LISTA_PEDIDOS_USUARIO_FAIL';

export const LISTA_PEDIDOS_REQUEST = 'LISTA_PEDIDOS_REQUEST';
export const LISTA_PEDIDOS_SUCCESS = 'LISTA_PEDIDOS_SUCCESS';
export const LISTA_PEDIDOS_FAIL = 'LISTA_PEDIDOS_FAIL';