export const LISTA_PRODUCTOS_REQUEST = 'LISTA_PRODUCTOS_REQUEST';
export const LISTA_PRODUCTOS_SUCCESS = 'LISTA_PRODUCTOS_SUCCESS';
export const LISTA_PRODUCTOS_FAIL = 'LISTA_PRODUCTOS_FAIL';

export const PRODUCTO_DETALLES_REQUEST = 'PRODUCTO_DETALLES_REQUEST';
export const PRODUCTO_DETALLES_SUCCESS = 'PRODUCTO_DETALLES_SUCCESS';
export const PRODUCTO_DETALLES_FAIL = 'PRODUCTO_DETALLES_FAIL';