export const LISTA_PRODUCTOS_REQUEST = 'LISTA_PRODUCTOS_REQUEST';
export const LISTA_PRODUCTOS_SUCCESS = 'LISTA_PRODUCTOS_SUCCESS';
export const LISTA_PRODUCTOS_FAIL = 'LISTA_PRODUCTOS_FAIL';

export const PRODUCTO_DETALLES_REQUEST = 'PRODUCTO_DETALLES_REQUEST';
export const PRODUCTO_DETALLES_SUCCESS = 'PRODUCTO_DETALLES_SUCCESS';
export const PRODUCTO_DETALLES_FAIL = 'PRODUCTO_DETALLES_FAIL';

export const PRODUCTO_GUARDADO_REQUEST = 'PRODUCTO_GUARDADO_REQUEST';
export const PRODUCTO_GUARDADO_SUCCESS = 'PRODUCTO_GUARDADO_SUCCESS';
export const PRODUCTO_GUARDADO_FAIL = 'PRODUCTO_GUARDADO_FAIL';

export const PRODUCTO_ELIMINADO_REQUEST = 'PRODUCTO_ELIMINADO_REQUEST';
export const PRODUCTO_ELIMINADO_SUCCESS = 'PRODUCTO_ELIMINADO_SUCCESS';
export const PRODUCTO_ELIMINADO_FAIL = 'PRODUCTO_ELIMINADO_FAIL';