export const USUARIO_INICIOSESION_REQUEST = 'USUARIO_INICIOSESION_REQUEST';
export const USUARIO_INICIOSESION_SUCCESS = 'USUARIO_INICIOSESION_SUCCESS';
export const USUARIO_INICIOSESION_FAIL = 'USUARIO_INICIOSESION_FAIL';