export const USUARIO_INICIOSESION_REQUEST = 'USUARIO_INICIOSESION_REQUEST';
export const USUARIO_INICIOSESION_SUCCESS = 'USUARIO_INICIOSESION_SUCCESS';
export const USUARIO_INICIOSESION_FAIL = 'USUARIO_INICIOSESION_FAIL';

export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST';
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS';
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL';

export const USUARIO_MODIFICARDATOS_REQUEST = 'USUARIO_MODIFICARDATOS_REQUEST';
export const USUARIO_MODIFICARDATOS_SUCCESS = 'USUARIO_MODIFICARDATOS_SUCCESS';
export const USUARIO_MODIFICARDATOS_FAIL = 'USUARIO_MODIFICARDATOS_FAIL';
export const USUARIO_MODIFICARDATOS_RESET = 'USUARIO_MODIFICARDATOS_RESET';

export const USUARIO_DETALLES_REQUEST = 'USUARIO_DETALLES_REQUEST';
export const USUARIO_DETALLES_SUCCESS = 'USUARIO_DETALLES_SUCCESS';
export const USUARIO_DETALLES_FAIL = 'USUARIO_DETALLES_FAIL';
export const USUARIO_DETALLES_RESET = 'USUARIO_DETALLES_RESET';

export const USUARIO_CIERRESESION_SUCCESS = 'USUARIO_CIERRESESION_SUCCESS';