export const USUARIO_INICIOSESION_REQUEST = 'USUARIO_INICIOSESION_REQUEST';
export const USUARIO_INICIOSESION_SUCCESS = 'USUARIO_INICIOSESION_SUCCESS';
export const USUARIO_INICIOSESION_FAIL = 'USUARIO_INICIOSESION_FAIL';

export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST';
export const USUARIO_REGISTRO_SUCCESS = 'USUARIO_REGISTRO_SUCCESS';
export const USUARIO_REGISTRO_FAIL = 'USUARIO_REGISTRO_FAIL';

export const USUARIO_CIERRESESION_SUCCESS = 'USUARIO_CIERRESESION_SUCCESS';